# ================================================================================
## JSON to mask
class_mapping:
    background: 0
    fissure souple: 1
    fissure souple reparee: 2
    depart de materiaux souple: 3
    desenrobage: 4
    remontee de fines: 5
    ressuage: 6
    depot de gomme: 7
    fissure rigide: 8
    fissure rigide reparee: 9
    depart de materiaux rigide: 10
    faiencage: 11
    defaut de joint: 12
    joint: 13
    vegetation: 14
    marquage: 15
    jonction: 16
    objet: 17
    autre: 18
# define priority: lowest priority first, highest priority last
priority_list:
    - marquage
    - faiencage
    - remontee de fines
    - depot de gomme
    - jonction
    - ressuage
    - joint
    - defaut de joint
    - desenrobage
    - fissure souple reparee
    - fissure rigide reparee
    - fissure souple
    - fissure rigide
    - depart de materiaux rigide
    - depart de materiaux souple
    - objet
    - vegetation
    - autre
boundary_settings:
    default:
        outside: 2
        inside: 1
    fissure souple:
        outside: 1
        inside: 2
# ================================================================================
## inference
colors:
    - [0, 0, 0]
    - [255, 0, 0]
    - [0, 255, 0]
    - [0, 0, 255]
    - [255, 255, 0]
    - [255, 0, 255]
    - [0, 255, 255]
    - [255, 128, 0]
    - [255, 0, 128]
    - [0, 255, 128]
    - [128, 255, 0]
    - [128, 0, 255]
    - [0, 128, 255]
    - [128, 0, 0]
    - [0, 128, 0]
    - [0, 0, 128]
    - [128, 128, 0]
    - [128, 0, 128]
    - [0, 128, 128]
# ================================================================================
## mosaic
input_dir: C:/Users/Admin/Data/mdm_p1 # C:/Users/Admin/Data/test_mosaic/raw_images # C:/Users/Admin/Data/mdm_p1
output_dir: C:/Users/Admin/Data/mdm_p1/mosaic # C:/Users/Admin/Data/test_mosaic/processed_images # C:/Users/Admin/Data/mdm_p1/mosaic
generate_mosaic: false
read_csv: true
# projection
crs_gps: EPSG:4326
crs_projected: EPSG:3944
heading_smoothing_window: 5
cam_offset_x: 0.0  # in meters
cam_offset_y: 2.5 # 3.7  # in meters
# image dimension
downscale_factor: 0.05
span_width: 3.0  # in meters
# stitching main method
stitch_downscale_factor: 0.25
orb_nfeatures: 3000
orb_ratio_threshold: 0.5
min_match_count: 20
ransac_threshold: 3.0
min_inlier_ratio: 0.6
# stitching additional methods
max_scale_deviation: 0.05
max_lateral_drift: 3.0  # in meters
max_angle_deviation_rad: 0.6  # in radians
vehicle_step: 1.5  # in meters
max_gps_kin_dist: 3.0  # in meters
# COG
merge_window_size: 2048
# display detections
generate_detections: true
detection_dir: C:/Users/Admin/Data/mdm_p1/mdm_p1_json
class2show:
    fissure souple: [255, 0, 0]
    vegetation: [255, 0, 0]
    fissure souple reparee: [0, 0, 255]
    depart de materiaux souple: [0, 255, 0]
# ================================================================================
## postprocessing
# true for linear defects, false for surface defects
class_type:
    fissure souple: true
    fissure souple reparee: true
    depart de materiaux souple: false
    desenrobage: false
    remontee de fines: false
    ressuage: false
    depot de gomme: false
    fissure rigide: true
    fissure rigide reparee: true
    depart de materiaux rigide: false
    faiencage: false
    defaut de joint: true
    vegetation: true
raster_res: 0.75  # in mm
bin_width: 2.5  # in mm
num_bins: 11