class_config: class_config
# ================================================================================
## JSON to mask
data_dir: C:/Users/Admin/Data/annotation/
ignore_index: 255
# ================================================================================
## train
seed: 42
name: pidnet_l  # deeplabv3+_mitb2
save_dir: C:/Users/Admin/Code/cbc_seg/output/
from_ckpt: true
# dataset
num_classes: 19
patch_per_img: 4
patch_size: 1024
# dataloader
batch_size: 4
num_workers: 16
# training
use_gpu: true
save_onnx: false
deterministic: false
lr: 3.e-4
eta_min: 1.e-6
weight_decay: 1.e-4
max_epochs: 200
accumulate_grad_batches: 4
log_every_n_steps: 10
# DeepLabV3+
tversky_alpha: 0.3  # Forgiving to thick boundaries (False Positives)
tversky_beta: 0.7  # Harsh on gaps (False Negatives)
# ================================================================================
## inference
eval_data_dir: C:/Users/Admin/Data/test_images/
version: version_0
result_dir: result/json
ckpt: epoch=164.ckpt
patch_per_row: 7
patch_per_col: 3
patch_overlap: 0.5
inference_workers: 32  # FYI: os.cpu_count() = 28
semaphore_lim: 256
# save to JSON
save_json: true
approx_epsilon_factor: 0.002
min_polygon_area: 250.0
edge_margin: 5