save_dir: C:\Users\Admin\Data\ba105_results
seed: 42
inference_flag: false
postprocessing_flag: true
# ================================================================================
## inference
ckpt_path: C:\Users\Admin\Code\cbc_seg\output\pidnet_l\version_1\checkpoints\epoch=973.ckpt
deterministic: false
# dataset
patch_per_row: 7
patch_per_col: 3
patch_size: 1024
patch_overlap: 0.5
name_format: path
# dataloader
num_workers: 8
use_gpu: true
# model
name: pidnet_l
num_classes: 19
ignore_index: 255
thread_workers: 32  # FYI: os.cpu_count() = 28
semaphore_lim: 256
class_mapping:
    background: 0
    fissure souple: 1
    fissure souple reparee: 2
    depart de materiaux souple: 3
    desenrobage: 4
    remontee de fines: 5
    ressuage: 6
    depot de gomme: 7
    fissure rigide: 8
    fissure rigide reparee: 9
    depart de materiaux rigide: 10
    faiencage: 11
    defaut de joint: 12
    joint: 13
    vegetation: 14
    marquage: 15
    jonction: 16
    objet: 17
    autre: 18
# save to JSON
save_json: true
approx_epsilon_factor: 0.002
min_polygon_area: 250.0
edge_margin: 5
# ================================================================================
## positioning
apply_correction: true
# projection
crs_gps: EPSG:4326
crs_projected: EPSG:3944
# camera offset
cam_offset_x: 0.0  # lateral, in meters
cam_offset_y: 3.88 # 3.7  # longitudinal, in meters
# smoothing
method: range
gps_error_variance: 0.5
# image dimension
downscale_factor: 0.05
span_width: 2.95  # in meters
# COG
merge_window_size: 2048
# define priority: lowest priority first, highest priority last
priority_list:
    - marquage
    - faiencage
    - remontee de fines
    - depot de gomme
    - jonction
    - ressuage
    - joint
    - defaut de joint
    - desenrobage
    - fissure souple reparee
    - fissure rigide reparee
    - fissure souple
    - fissure rigide
    - depart de materiaux rigide
    - depart de materiaux souple
    - objet
    - vegetation
    - autre
# display detections
class2show:
    fissure souple: [255, 0, 0]
    vegetation: [255, 0, 0]
    fissure souple reparee: [0, 0, 255]
    depart de materiaux souple: [0, 255, 0]
# ================================================================================
## postprocessing
# true for linear defects, false for surface defects
class_type:
    fissure souple: true
    fissure souple reparee: true
    depart de materiaux souple: false
    desenrobage: false
    remontee de fines: false
    ressuage: false
    depot de gomme: false
    fissure rigide: true
    fissure rigide reparee: true
    depart de materiaux rigide: false
    faiencage: false
    defaut de joint: true
    vegetation: true
raster_res: 0.75  # in mm
bin_width: 2.5  # in mm
num_bins: 11
chunk_size_m: 5.  # in m